In [2]:
import numpy as np
import matplotlib as plt

In [4]:
def up(i):
    is_boundary(i)

2


In [27]:
L = 5
N = L ** 2

elements = np.zeros(N)

viz = np.empty((N, 4), dtype=np.int16)

for i in range(N):
    if (i % L == L - 1): # dir
        right = i - L + 1
    else:
        right = i + 1

    viz[i][0] = right

    if (i >= (L ** 2) - L): # cima
        up = i - N + L
    else:
        up = i + L

    viz[i][1] = up
    
    if (i % L == 0): # esq
        left = i + L - 1
    else:
        left = i - 1
        
    viz[i][2] = left
    
    if (i < L): # baixo
        down = i + N - L
    else:
        down = i - L

    viz[i][3] = down
    
print(viz)

[[ 1  5  4 20]
 [ 2  6  0 21]
 [ 3  7  1 22]
 [ 4  8  2 23]
 [ 0  9  3 24]
 [ 6 10  9  0]
 [ 7 11  5  1]
 [ 8 12  6  2]
 [ 9 13  7  3]
 [ 5 14  8  4]
 [11 15 14  5]
 [12 16 10  6]
 [13 17 11  7]
 [14 18 12  8]
 [10 19 13  9]
 [16 20 19 10]
 [17 21 15 11]
 [18 22 16 12]
 [19 23 17 13]
 [15 24 18 14]
 [21  0 24 15]
 [22  1 20 16]
 [23  2 21 17]
 [24  3 22 18]
 [20  4 23 19]]
